### ISSUE TITLE
Buffer Data Type Mismatch in Kmeans_Clustering

### ISSUE THREAD

**Issue by TeddyMorales** [rafaljanwojcik/Unsupervised-Sentiment-Analysis#2]
Hello, this is a really interesting project and I thank you for making it available to the open-source community!

After cloning the repo and trying to run everything locally, ran into an error in the k_means clustering notebook

**Versions**:
python = 3.6.10
pandas = 1.0.4
numpy = 1.18.5
sklearn = 0.23.1
gensim = 3.8.0 

**Cell that causes issue**:
```
words = pd.DataFrame(word_vectors.vocab.keys())
words.columns = ['words']
words['vectors'] = words.words.apply(lambda x: word_vectors.wv[f'{x}'])
words['cluster'] = words.vectors.apply(lambda x: model.predict([x]))
words.cluster = words.cluster.apply(lambda x: x[0])
```
**Output of sklearn model.predict using unmodified code**:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-32f4e2e19783> in <module>
      2 words.columns = ['words']
      3 words['vectors'] = words.words.apply(lambda x: word_vectors.wv[f'{x}'])
----> 4 words['cluster'] = words.vectors.apply(lambda x: model.predict([x]))
      5 words.cluster = words.cluster.apply(lambda x: x[0])

~/miniconda3/envs/Alpha/lib/python3.6/site-packages/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
   3846             else:
   3847                 values = self.astype(object).values
-> 3848                 mapped = lib.map_infer(values, f, convert=convert_dtype)
   3849 
   3850         if len(mapped) and isinstance(mapped[0], Series):

pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()

<ipython-input-12-32f4e2e19783> in <lambda>(x)
      2 words.columns = ['words']
      3 words['vectors'] = words.words.apply(lambda x: word_vectors.wv[f'{x}'])
----> 4 words['cluster'] = words.vectors.apply(lambda x: model.predict([x]))
      5 words.cluster = words.cluster.apply(lambda x: x[0])

~/miniconda3/envs/Alpha/lib/python3.6/site-packages/sklearn/cluster/_kmeans.py in predict(self, X, sample_weight)
   1186 
   1187         return _labels_inertia(X, sample_weight, x_squared_norms,
-> 1188                                self.cluster_centers_, self._n_threads)[0]
   1189 
   1190     def score(self, X, y=None, sample_weight=None):

~/miniconda3/envs/Alpha/lib/python3.6/site-packages/sklearn/cluster/_kmeans.py in _labels_inertia(X, sample_weight, x_squared_norms, centers, n_threads)
    654     _labels(X, sample_weight, x_squared_norms, centers, centers,
    655             weight_in_clusters, labels, center_shift, n_threads,
--> 656             update_centers=False)
    657 
    658     inertia = _inertia(X, sample_weight, centers, labels)

sklearn/cluster/_k_means_lloyd.pyx in sklearn.cluster._k_means_lloyd.lloyd_iter_chunked_dense()

ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
```

Thinking its an issue with the versions of modules I am using, was wondering if you could point me in right direction! 

Thanks!

**Comment by mmchougule** [comment]
@TeddyMorales did you solve this issue? I am seeing the same one.

**Comment by rafaljanwojcik** [comment]
Hello, thank you for reporting this issue, just by quickly looking at the code, in notebook: https://github.com/rafaljanwojcik/Unsupervised-Sentiment-Analysis/blob/master/KMeans_clustering/KMeans_clustering.ipynb

```
words = pd.DataFrame(word_vectors.vocab.keys())
words.columns = ['words']
words['vectors'] = words.words.apply(lambda x: word_vectors.wv[f'{x}'])
words['cluster'] = words.vectors.apply(lambda x: model.predict([np.array(x)]))
words.cluster = words.cluster.apply(lambda x: x[0])
```

there is the part: `words['cluster'] = words.vectors.apply(lambda x: model.predict([x]))` in your error message, but in the notebook there is `words['cluster'] = words.vectors.apply(lambda x: model.predict([np.array(x)])`, could you try with this change, and see if it works? If not, I will do my best tomorrow to resolve this issue :)

**Comment by mmchougule** [comment]
I've tried with `words.vectors.apply(lambda x: model.predict([np.array(x)]))`, same error. When I do `words["vectors"][0].dtype` and `words["vectors"][0][0].dtype` both are `dtype('float32')`. I think I need to iterate over each vector values in each row and cast with `.astype("double")`.

**Comment by rafaljanwojcik** [comment]
Okay, let me know if it works. You might also simply pass to lambda function `np.array(x, dtype='double')`

**Comment by mmchougule** [comment]
`np.array(x, dtype='double')` didn't work for some reason. Creating a PR with a fix.

**Comment by mmchougule** [comment]
#3 PR created. Please let me know if any questions. :)

**Comment by rafaljanwojcik** [comment]
Great thanks for your contribution! :) I will review it in upcoming days :)

**Comment by rafaljanwojcik** [comment]
Accepted PR, sorry it took so long. If you have any additional ideas, it will be great to see them too! :)

**Comment by AndromRyan** [comment]
The issue still present with fix
Python== 3.7.6
scikit-learn==0.23.2
pandas==1.1.3
numpy==1.18.5
gensim==3.8.3

`def cast_vector(row):
    return np.array(list(map(lambda x: x.astype('double'), row)))

words = pd.DataFrame(word_vectors.vocab.keys())
words.columns = ['words']
words['vectors'] = words.words.apply(lambda x: word_vectors.wv[f'{x}'])
words['vectors_typed'] = words.vectors.apply(cast_vector)
words['cluster'] = words.vectors_typed.apply(lambda x: model.predict([np.array(x)]))
words.cluster = words.cluster.apply(lambda x: x[0])

words['cluster_value'] = [1 if i==0 else -1 for i in words.cluster]
words['closeness_score'] = words.apply(lambda x: 1/(model.transform([x.vectors]).min()), axis=1)
words['sentiment_coeff'] = words.closeness_score * words.cluster_value`

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-a087c14dd0ec> in <module>
      6 words['vectors'] = words.words.apply(lambda x: word_vectors.wv[f'{x}'])
      7 words['vectors_typed'] = words.vectors.apply(cast_vector)
----> 8 words['cluster'] = words.vectors_typed.apply(lambda x: model.predict([np.array(x)]))
      9 words.cluster = words.cluster.apply(lambda x: x[0])
     10 

/opt/conda/lib/python3.7/site-packages/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
   4198             else:
   4199                 values = self.astype(object)._values
-> 4200                 mapped = lib.map_infer(values, f, convert=convert_dtype)
   4201 
   4202         if len(mapped) and isinstance(mapped[0], Series):

pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()

<ipython-input-27-a087c14dd0ec> in <lambda>(x)
      6 words['vectors'] = words.words.apply(lambda x: word_vectors.wv[f'{x}'])
      7 words['vectors_typed'] = words.vectors.apply(cast_vector)
----> 8 words['cluster'] = words.vectors_typed.apply(lambda x: model.predict([np.array(x)]))
      9 words.cluster = words.cluster.apply(lambda x: x[0])
     10 

/opt/conda/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py in predict(self, X, sample_weight)
   1203 
   1204         return _labels_inertia(X, sample_weight, x_squared_norms,
-> 1205                                self.cluster_centers_, self._n_threads)[0]
   1206 
   1207     def score(self, X, y=None, sample_weight=None):

/opt/conda/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py in _labels_inertia(X, sample_weight, x_squared_norms, centers, n_threads)
    658     _labels(X, sample_weight, x_squared_norms, centers, centers,
    659             weight_in_clusters, labels, center_shift, n_threads,
--> 660             update_centers=False)
    661 
    662     inertia = _inertia(X, sample_weight, centers, labels)

sklearn/cluster/_k_means_lloyd.pyx in sklearn.cluster._k_means_lloyd.lloyd_iter_chunked_dense()

ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
`

**Comment by rafaljanwojcik** [comment]
@AndromRyan thanks for reporting it, I pushed fix to branch data_type_fix, could you review if it works? Please comment in PR https://github.com/rafaljanwojcik/Unsupervised-Sentiment-Analysis/pull/5

**Comment by StevenZxy** [comment]
`model = KMeans(n_clusters=2, max_iter=1000, random_state=True, n_init=50).fit(X=word_vectors.vectors.astype(np.float))`

explicitly set the type to float before fitting should work.

**Comment by rafaljanwojcik** [comment]
I created fix by specifying `np.double` to fix this issue, did you try it? See: https://github.com/rafaljanwojcik/Unsupervised-Sentiment-Analysis/pull/5

**Comment by rafaljanwojcik** [comment]
Hopefully solved, closing issue :)

**Comment by rafaljanwojcik** [comment]
Hopefully solved, closing issue :)
