### ISSUE TITLE
How positive and negative sentiment clusters identified?

### ISSUE THREAD

**Issue by madhubandru** [rafaljanwojcik/Unsupervised-Sentiment-Analysis#6]
Hi,

I could see in KMeans clustering model positive and negative cluster centers are defined by not used again. 

`positive_cluster_index = 1`
`	positive_cluster_center = model.cluster_centers_[0]`
`negative_cluster_center = model.cluster_centers_[1]`

Can you help me to understand how you are differentiating which cluster (among 2 clusters) is positive sentiment and negative sentiment and how the positive cluster index value picked as 1?

Thank you in advance!

**Comment by rafaljanwojcik** [comment]
Hello,
 
I'm happy you're using the repo :) The answer is pretty simple - I sample words from each cluster and manually verify if most of them are relatively positive or negative. If you'd like to automate this step, you could prepare two sets of words that your'e sure should be positive or negative, and check in which cluster they are. Let me know if that answer solves your issue 

Best regards
Rafał
