### ISSUE TITLE
'KMeans' object has no attribute 'wv'

### ISSUE THREAD

**Issue by girolamodaschio** [rafaljanwojcik/Unsupervised-Sentiment-Analysis#9]
Hi Rafael,

I'm having issues on running your awesome pipeline locally.
In detail, when I call `words = list(model.wv.index_to_key)` on KMeans_clustering notebook, I run into 

`AttributeError: 'KMeans' object has no attribute 'wv'`

Could you help?
Thanks in advance.

![image](https://user-images.githubusercontent.com/58935223/139284436-52cdf69a-6c55-4ef4-b3bc-5b5b7ea47198.png)

**Comment by rubenvisser22** [comment]
Do you know the solution?

**Comment by rafaljanwojcik** [comment]
Hey, I posted an update directly to master, let me know if it solves this issue

**Comment by rubenvisser22** [comment]
Hey Thanks for the fast reply. I fixed by changing the name of the K-Means model. The word2vec name was the same name as the K-means name.

**Comment by rafaljanwojcik** [comment]
Yeah, noticed that there was some naming mistake, in original code they were named differently. Nevertheless, there was also an issue in original code, as in gensim the way of obtaining Word2Vec vocab has changed, so I updated it, everything should be working now, if you install required packages versions based on requirements.txt file I also added
